name: Deploy para Produção

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar SSH e Deploy
        uses: appleboy/ssh-action@v1.0.3 # Use uma versão específica para evitar quebras futuras
        with:
          host: ${{ secrets.SSH_HOST }} # É uma boa prática usar segredos para todas as informações sensíveis
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/containers/chamada
            git pull origin main
            docker-compose down
            docker-compose up -d --build --force-recreate
            docker system prune -af --filter "until=24h" # Opcional